//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRacingProfiles.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iRacingProfiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current:.
        /// </summary>
        public static string current_label {
            get {
                return ResourceManager.GetString("current_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string delete_label {
            get {
                return ResourceManager.GetString("delete_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File does not exist.
        /// </summary>
        public static string exception_file_exists {
            get {
                return ResourceManager.GetString("exception_file_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder does not exist.
        /// </summary>
        public static string exception_folder_exists {
            get {
                return ResourceManager.GetString("exception_folder_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile name cannot be empty.
        /// </summary>
        public static string exception_profile_empty_name {
            get {
                return ResourceManager.GetString("exception_profile_empty_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This profile already exists.
        /// </summary>
        public static string exception_profile_exists {
            get {
                return ResourceManager.GetString("exception_profile_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile name cannot contain dots or slashes (\\ or /).
        /// </summary>
        public static string exception_profile_name {
            get {
                return ResourceManager.GetString("exception_profile_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a profile to delete it..
        /// </summary>
        public static string exception_profile_selected {
            get {
                return ResourceManager.GetString("exception_profile_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File:.
        /// </summary>
        public static string file_label {
            get {
                return ResourceManager.GetString("file_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iRacing folder:.
        /// </summary>
        public static string folder_label {
            get {
                return ResourceManager.GetString("folder_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lang.
        /// </summary>
        public static string menu_lang {
            get {
                return ResourceManager.GetString("menu_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the profile and its file?.
        /// </summary>
        public static string messagebox_del_confirm_msg {
            get {
                return ResourceManager.GetString("messagebox_del_confirm_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete confirmation.
        /// </summary>
        public static string messagebox_del_confirm_title {
            get {
                return ResourceManager.GetString("messagebox_del_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string name_label {
            get {
                return ResourceManager.GetString("name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string new_label {
            get {
                return ResourceManager.GetString("new_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile:.
        /// </summary>
        public static string profile_label {
            get {
                return ResourceManager.GetString("profile_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string save_label {
            get {
                return ResourceManager.GetString("save_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        public static string select_label {
            get {
                return ResourceManager.GetString("select_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iRacing Profile Tool.
        /// </summary>
        public static string title_label {
            get {
                return ResourceManager.GetString("title_label", resourceCulture);
            }
        }
    }
}
